#!/usr/bin/env bash
# Prints Best School using while loop
i=0
j=1
while [ $i -lt 13 ]; do
    echo "Hour: $i"
      while [ $j -lt 60 ]; do
	  echo "$j"
	  ((j++))
      done
      j=1
      ((i++))
done
